ci: fix docker size debug

diff --git a/.github/workflows/release-strapi-docker.yml b/.github/workflows/release-strapi-docker.yml
--- a/.github/workflows/release-strapi-docker.yml
+++ b/.github/workflows/release-strapi-docker.yml
@@ -64,7 +64,17 @@ jobs:
         run: |
           docker image inspect ${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
 
-      - name: Debug size
+      - name: 💾 Save docker image
+        run: docker save ${{ env.IMAGE }}:${{ steps.meta.outputs.version }} -o ./docker-image.tar
+
+      - name: 📐 Compress saved image and show size
+        env:
+          MAX_SIZE_IN_MB: 80
+          ZSTD_LEVEL: 8
         run: |
-          docker save ${{ env.IMAGE }}:${{ steps.meta.outputs.version }} | gzip > ./${{ env.IMAGE }}-${{ steps.meta.outputs.version }}.tar.gz
-          ls -lah ./${{ env.IMAGE }}-${{ steps.meta.outputs.version }}.tar.gz
+          zstd -${{ env.ZSTD_LEVEL }} -i ./docker-image.tar -o ./docker-image.tar.zst          
+          ls -lah | grep docker-image.tar
+          if [ $(ls -s --block-size=1048576 ./docker-image.tar.zst | cut -d' ' -f1)  -gt ${{ env.MAX_SIZE_IN_MB }} ]; then 
+             echo 'Error: docker image too big'; 
+             exit 1; 
+          else echo "Size ok"; fi
